"use client";

import { useState } from "react";

interface ExportButtonProps {
  title: string;
  content: string;
}

export default function ExportButton({ title, content }: ExportButtonProps) {
  const [exporting, setExporting] = useState(false);

  function handleExport() {
    setExporting(true);

    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      setExporting(false);
      return;
    }

    printWindow.document.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', sans-serif; padding: 40px; color: #1a1a1a; line-height: 1.6; }
    h1 { font-size: 24px; font-weight: 700; margin-bottom: 8px; }
    .subtitle { color: #666; font-size: 14px; margin-bottom: 24px; }
    .content { font-size: 14px; }
    .content h2 { font-size: 18px; font-weight: 600; margin: 20px 0 8px; }
    .content h3 { font-size: 15px; font-weight: 600; margin: 16px 0 6px; }
    .content p { margin-bottom: 12px; }
    .content ul { margin: 8px 0 12px 20px; }
    .content li { margin-bottom: 4px; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e5e5; font-size: 11px; color: #999; }
    @media print {
      body { padding: 20px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <div class="subtitle">BASR | UAE Sentiment Intelligence | ${new Date().toLocaleDateString("en-AE", { year: "numeric", month: "long", day: "numeric" })}</div>
  <div class="content">${content}</div>
  <div class="footer">
    Generated by BASR (بصر) - Real-time UAE Sentiment Intelligence<br>
    https://dashboard-gamma-roan-31.vercel.app
  </div>
  <script>window.onload = function() { window.print(); }</script>
</body>
</html>`);
    printWindow.document.close();

    setTimeout(() => setExporting(false), 1000);
  }

  return (
    <button
      onClick={handleExport}
      disabled={exporting}
      className="inline-flex items-center gap-1.5 rounded-lg border border-line bg-surface px-3 py-1.5 text-[12px] font-medium text-ink-2 transition-all hover:border-accent/40 hover:text-accent disabled:opacity-50"
    >
      <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
      </svg>
      {exporting ? "Exporting..." : "Export PDF"}
    </button>
  );
}
